server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
    name: content
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

